server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 10800

spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    tomcat:
      max-idle: 10
      max-wait: 10000
      min-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
  freemarker:
    cache: false
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1



ftp:
  host: 127.0.0.2
  username: user
  password: user
